### ISSUE TITLE
Toolbox not reading the cardiac PPU modality from Biopac.mat

### ISSUE THREAD

**Issue by mdurandruel** [translationalneuromodeling/tapas#103]
Dear Lars,

First, thank you very much for this amazing toolbox. I just have one issue. I am using Biopac to record the physiological signals. I have the respiration and PPU data as well as the triggers from the MRI in my .mat file. 

When using the toolbox, only the respiratory regressors are created. I think I know where the problem is. In tapas_physio_read_physlogfiles_biopac_mat.m, the script does not take into account the cardiac modality I have. 

First for iChosenModality ( l120), I think that as the cardiac_modality is PPU, it does not recognise it in cardiacModalityArray where one of the cell is 'ppu' in small letters.

Second my labels of transducers are RSP100C, PPG100C and Digital input (created at l94 of the same function). 
Thus as the labels considered in your script are just ECG100C, it does not take into account the label I have (at line132). 

Please find attached one physio file from one of my subject.
[sub1_ses1.mat.gz](https://github.com/translationalneuromodeling/tapas/files/4954860/sub1_ses1.mat.gz)

I hope these are the only issues, for now I can only debug until this point.

I thank you for your consideration and am very grateful for your work!

Best regards,

Manon

**Comment by mrikasper** [comment]
Dear Manon,

I am terribly sorry for not responding to your question earlier. It's been crazy a spring and summer here in Toronto with 5 months of daycare closure, so my capacities were rather limited, and when I got back to work properly, your issue somehow got overlooked.

You had actually solved the puzzle nearly by yourself (and meanwhile might have done so completely): I think all you have to do is change the last entry of the `cardiacModalityArray` from `ECG100C` to `PPG100C`, and make the check for the cardiac modality case-insensitive by using `lower`. 

Here are the adapted lines of code for `tapas_physio_read_physlogfiles_biopac_mat` that I will include in the next release:

```
labelsCardiacArray = ...
    {'C0 - Comb Band Stop Filter', 'C1 - Filter', 'ECG100C', 'ECG100C', ...
    'PPG100C'};

iChosenModality =  tapas_physio_find_string(cardiacModalityArray, ...
    lower(cardiac_modality));
```

The output looks reasonable to me (but I used some random scan timing parameters), I have attached the SPM job file (just rename to `.m`)

![image](https://user-images.githubusercontent.com/13321311/96514362-8a6c8f80-1231-11eb-8262-487511858fd0.png)

[physio_spm_job_biopac_mat.txt](https://github.com/translationalneuromodeling/tapas/files/5404922/physio_spm_job_biopac_mat.txt)

I hope that (still) helps.

My apologies again and all the best,
Lars
