### ISSUE TITLE
PhysIOToolbox gives "Matrix index is out of range for deletion."

### ISSUE THREAD

**Issue by Gilles86** [translationalneuromodeling/tapas#122]
Hi Lars (@mrikasper),

Compliments on the amazing toolbox (it is the only reason I have still Matlab installed) and I hope you are doing well in Canada.

I'm currently analyzing a data set I collected at the 7T in Zurich you know very well. The PhysIOToolbox works great, pretty much out-of-the-box. However, I stumbled upon a weird error for one specific run, where, as far as I can see, nothing crazy happened. Any clue what is going on here?

```
Matrix index is out of range for deletion.

Error in tapas_physio_get_template_from_pulses (line 93)
template(1,:) = [];

Error in tapas_physio_get_cardiac_pulse_template (line 136)
[pulseCleanedTemplate, pulseTemplate] = tapas_physio_get_template_from_pulses(...

Error in tapas_physio_get_cardiac_pulses_auto_matched (line 55)
    tapas_physio_get_cardiac_pulse_template(t, c, verbose, ...

Error in tapas_physio_get_cardiac_pulses (line 93)
                    tapas_physio_get_cardiac_pulses_auto_matched( ...

Error in tapas_physio_main_create_regressors (line 172)
                            tapas_physio_get_cardiac_pulses(ons_secs.t, ons_secs.c, ...

Error in prepare_retroicor (line 120)
        physio = tapas_physio_main_create_regressors(physio);

Error in prepare_retroicor_all (line 4)
        prepare_retroicor(subject, char(session));
```

You can find the Matlab method I use to set up the `physio`-object here:
https://github.com/Gilles86/risk_experiment/blob/master/risk_experiment/physiology/prepare_retroicor.m

Cheers,
Gilles

**Comment by mrikasper** [comment]
Dear Gilles,

very nice to hear from you - and also that PhysIO is useful for you (maybe I should start charging Matlab for referrals ;-))!

It looks as if the cardiac peak detection fails very early on, which could have a number of reasons (amplitude range, synchronization, recording SNR). Can you share a screenshot of the raw data that was read in? Or maybe the data itself (also privately, you can contact me by e-mail)?

Thank you and all the best,
Lars

PS: We are doing well in Canada, given the pandemic and everything, but I do miss the earlier spring in Zurich. Hope you are enjoying Switzerland!
