### ISSUE TITLE
PhysIO findpeaks error with example data

### ISSUE THREAD

**Issue by dariusvalevicius** [translationalneuromodeling/tapas#124]
Hi,

I'm just getting started with testing example data (sans SPM) and running up against this error log with all the datasets I've tried so far, when running tapas_physio_main_create_regressors() :

> Error using tapas_physio_log (line 56)
> tapas_physio_findpeaks_compatible is no longer
> distributed with this toolbox. Instead, we rely on the "findpeaks"
> function included in Matlab's Signal Processing Toolbox.
> 
> Error in tapas_physio_findpeaks (line 43)
>     tapas_physio_log(sprintf(...
> 
> Error in tapas_physio_get_cardiac_pulse_template (line 49)
> [tmp, cpulse1stGuess] = tapas_physio_findpeaks( ...
> 
> Error in tapas_physio_get_cardiac_pulses_auto_matched (line 55)
>     tapas_physio_get_cardiac_pulse_template(t, c, verbose, ...
> 
> Error in tapas_physio_get_cardiac_pulses (line 93)
>                     tapas_physio_get_cardiac_pulses_auto_matched( ...
> 
> Error in tapas_physio_main_create_regressors (line 172)
>                             tapas_physio_get_cardiac_pulses(ons_secs.t, ons_secs.c, ...
> 
> Error in siemens_hcp_ppu3t_matlab_script (line 65)
> physio = tapas_physio_main_create_regressors(physio);

This is with the latest version of tapas (4.0.0) and MATLAB 2020b. Any help would be much appreciated!

Thanks,
Darius

**Comment by mrikasper** [comment]
Dear Darius,

thank you for your interest in the PhysIO Toolbox! Does your Matlab version contain the Signal Processing Toolbox, or could you install it?

[`findpeaks`](https://mathworks.com/help/signal/ref/findpeaks.html) is a function provided by Mathworks' toolbox that our cardiac and some respiratory time series preprocessing relies upon. In principle, you could replace it by any open-source peak detection algorithm you find, but we have only tested PhysIO with this one.

I hope this helps!

All the best,
Lars
