### ISSUE TITLE
Error message when running script

### ISSUE THREAD

**Issue by katamolnar** [translationalneuromodeling/tapas#136]
Hi! I get this error message when I try to run PhysIO script with respiratory and cardiac data:
![image](https://user-images.githubusercontent.com/53969497/117447429-cf41e480-af3d-11eb-969b-f1df3fd16108.png)
![image](https://user-images.githubusercontent.com/53969497/117447463-d8cb4c80-af3d-11eb-92a3-0071057113f8.png)

To enter the information about the data I used a guide that has worked well in the past. Here are the specifications:
![image](https://user-images.githubusercontent.com/53969497/117447532-ef71a380-af3d-11eb-9889-5ffb15081394.png)
![image](https://user-images.githubusercontent.com/53969497/117447546-f39dc100-af3d-11eb-8691-f2bb123179e1.png)
![image](https://user-images.githubusercontent.com/53969497/117447567-f7c9de80-af3d-11eb-8035-c070148c8a48.png)
![image](https://user-images.githubusercontent.com/53969497/117447577-fbf5fc00-af3d-11eb-821c-b045862ed60d.png)
![image](https://user-images.githubusercontent.com/53969497/117447595-00bab000-af3e-11eb-87af-8fe9b60760bf.png)

I tried to find the problem but I'm not very familiar with the toolbox and so far, it’s I couldn't solve it. Do you know what the issue might be?
Thank you for your help in advance!
Kata

P.s: In case it's helpful, the above error message occurs with the latest version of Tapas PhysIO. Before I updated to the most recent version, I was using a beta version from 2015 (it was the first version made for Seimens MRIs, which a collaborator obtained from Lars Kasper via email). In the beta version I received a different error message when I used the same files and parameters as depicted above. This is the message that I receive in beta: Error when running the script: Array indices must be positive integers or logical values.

**Comment by mrikasper** [comment]
Dear Kata,

my apologies for the late reply, with ISMRM and the pandemic still going on. Line 88 in `tapas_physio_siemens_table2cardiac` computes 

```
endClipSamples = floor(endCropSeconds/dt);
```

Presumably one of the two variables is not set properly. It might be that `dt` has two values (for cardiac and resp. data) or that the crop is empty. Could you check these values via a breakpoint on error, please? Alternatively, you can also send me the SPM batch file and the logfiles via e-mail and I try to reproduce the error.

All the best,
Lars

**Comment by mrikasper** [comment]
Dear Kata,

thank you for providing the logfiles and matlabbatch. There were two errors in the batch specification:

1. Your logfile `vendor` is `BioPac_mat`, not `Siemens_VB`. Therefore, the wrong readin function was used by the toolbox
2.  `TR` has to be specified in seconds (not milliseconds), which invoked an out-of-memory error when padding the data. Usually SI units are used in PhysIO, but if unsure, you can always check the info window in the batch editor about each parameter (see screenshot).

With these adjustments, your example runs through on my system. However, your ECG data looks irregular: no clear R-peak, there seem to be several (Q? S?) subpeaks of near-equal amplitude, making peak detection for cardiac RETROICOR hard. You can see this in the Preproc Diagnostics Plot. Can you check for other subjects whether this is a recurring issue? The respiratory data looks fine though.

![image](https://user-images.githubusercontent.com/13321311/120032699-90e19780-bfc8-11eb-9349-bba928d4ec01.png)
[scripts_job_LK.txt](https://github.com/translationalneuromodeling/tapas/files/6562942/scripts_job_LK.txt)

![image](https://user-images.githubusercontent.com/13321311/120032357-1153c880-bfc8-11eb-86d6-b638a4ec201b.png)

All the best,
Lars
