### ISSUE TITLE
Physio Siemens log files

### ISSUE THREAD

**Issue by acmv1216** [translationalneuromodeling/tapas#172]
Dear colleague, 

Many thanks for the toolbox, is really great. I have used it in the past with data from Philips scanner, without an issue. 

Now I want to use it with data from Siemens scanner, for which I have *PULS.log and *AcquisitionTime.log files. The first one I entered into the log_cardiac and the second in the log_scan_timing and set up the scan/Physio sync with the scan timing log. However, it gets stuck at the tapas_physio_get_onsets_from_locs.m step. I must be doing sth very basic wrong, but I would be extremely grateful if you could let me know where the issue might be. 

Thakns!

**Comment by mrikasper** [comment]
Dear @acmv1216,

Thank you for using PhysIO and giving it a chance on another vendor's system :-)

From what you describe, you set up PhysIO exactly the right way for your Siemens scanner. To facilitate helping you, could you answer the following questions, please?

1. Which version of scanner software (VB, VD/VE or XA?) are you using?
    - I know that the physiological logfile format (`.ecg', `.puls` files) changed for XA, and I am currently working on supporting this change.
2. Do you use any non-standard sequence (e.g., CMRR SMS/multiband)? 
    - the file formats used by CMRR and also HCP differ from the Siemens native, and their specification changed several times in the past
    - If you are able to share, could you attach (or send me via e-mail) an example `*PULS.log` or `*AcquisitionTime.log` file?
3. Could you send me a copy of the error message in Matlab you receive in `tapas_physio_get_onsets_from_locs.m`.
4. Ideally, could you also save and send the SPM batch file (as `.m`) or matlab script you use to call PhysIO?
5. Which version of PhysIO (`tapas_physio_version`) are you using?

Looking forward to your response and

All the best,
Lars

**Comment by acmv1216** [comment]
Dear Lars, 

Many thanks for the speedy reply! 

Glad to hear I was having the right input at least that is not too far from what it should be... 

I am afraid I do not know the answer to all of your questions, but I can send you the info I get. 

1. First, this is not data I have collected so I do not know about the scanner software. I am assuming this must be somewhere in the data - maybe you can point me to the file containing that info? 

2. Regarding sequence, no, I do not see any particular non-standard sequence. Details are as follows: a 20-channel phased-array radio frequency head coil, T2*-weighted echo-planar imaging (EPI) data were acquired with interleaved acquisition mode, 39 axial slices of 3-mm thickness, 0.5-mm interslice gap, field of view 228 × 228 mm2 and an in-plane resolution of 3 × 3 mm2. The repetition time was 2.5 s, the echo time was 30 ms, and the bandwidth was set to 2350 Hz/ pixel.
I also send you attached an example of the log files used. Let me know if you cannot see them. 
[20150304_151945_AcquisitionInfo_EPI_fMRI_Cyberball_Round1.log](https://github.com/translationalneuromodeling/tapas/files/8063545/20150304_151945_AcquisitionInfo_EPI_fMRI_Cyberball_Round1.log)

[20150304_152728_PULS.log](https://github.com/translationalneuromodeling/tapas/files/8063684/20150304_152728_PULS.log)



3. Error
```
`Failed  'TAPAS PhysIO Toolbox'
Array indices must be positive integers or logical values.
In file "/Applications/spm12/toolbox/PhysIO/tapas_physio_get_onsets_from_locs.m" (???), function "tapas_physio_get_onsets_from_locs" at line 105.
In file "/Applications/spm12/toolbox/PhysIO/tapas_physio_create_scan_timing.m" (???), function "tapas_physio_create_scan_timing" at line 114.
In file "/Applications/spm12/toolbox/PhysIO/tapas_physio_main_create_regressors.m" (???), function "tapas_physio_main_create_regressors" at line 138.
In file "/Applications/spm12/toolbox/PhysIO/tapas_physio_cfg_matlabbatch.m" (???), function "run_physio" at line 1463.

The following modules did not run:
Failed: TAPAS PhysIO Toolbox`
```


4. Batch file `matlabbatch{1}.spm.tools.physio.save_dir = {'/Volumes/JW_min/JW/Ana_analyses/035'};
matlabbatch{1}.spm.tools.physio.log_files.vendor = 'Siemens_Tics';
matlabbatch{1}.spm.tools.physio.log_files.cardiac = {'/Volumes/JW_min/JW/data_johannes/BION_logs_physio/Franziska_Auswertung/bion_fmri_035/Neuer Ordner/20150304_151945_PULS.log'};
matlabbatch{1}.spm.tools.physio.log_files.respiration = {''};
matlabbatch{1}.spm.tools.physio.log_files.scan_timing = {'/Volumes/JW_min/JW/data_johannes/BION_logs_physio/Franziska_Auswertung/bion_fmri_035/Neuer Ordner/20150304_151945_AcquisitionInfo_EPI_fMRI_Cyberball_Round1.log'};
matlabbatch{1}.spm.tools.physio.log_files.sampling_interval = 0.0025;
matlabbatch{1}.spm.tools.physio.log_files.relative_start_acquisition = 0;
matlabbatch{1}.spm.tools.physio.log_files.align_scan = 'last';
matlabbatch{1}.spm.tools.physio.scan_timing.sqpar.Nslices = 39;
matlabbatch{1}.spm.tools.physio.scan_timing.sqpar.NslicesPerBeat = [];
matlabbatch{1}.spm.tools.physio.scan_timing.sqpar.TR = 2.5;
matlabbatch{1}.spm.tools.physio.scan_timing.sqpar.Ndummies = 3;
matlabbatch{1}.spm.tools.physio.scan_timing.sqpar.Nscans = 76;
matlabbatch{1}.spm.tools.physio.scan_timing.sqpar.onset_slice = 19;
matlabbatch{1}.spm.tools.physio.scan_timing.sqpar.time_slice_to_slice = [];
matlabbatch{1}.spm.tools.physio.scan_timing.sqpar.Nprep = [];
matlabbatch{1}.spm.tools.physio.scan_timing.sync.scan_timing_log = struct([]);
matlabbatch{1}.spm.tools.physio.preproc.cardiac.modality = 'ECG';
matlabbatch{1}.spm.tools.physio.preproc.cardiac.initial_cpulse_select.auto_matched.min = 0.4;
matlabbatch{1}.spm.tools.physio.preproc.cardiac.initial_cpulse_select.auto_matched.file = 'initial_cpulse_kRpeakfile.mat';
matlabbatch{1}.spm.tools.physio.preproc.cardiac.posthoc_cpulse_select.off = struct([]);
matlabbatch{1}.spm.tools.physio.model.output_multiple_regressors = 'multiple_regressors_R1.txt';
matlabbatch{1}.spm.tools.physio.model.output_physio = 'physio_R1.mat';
matlabbatch{1}.spm.tools.physio.model.orthogonalise = 'none';
matlabbatch{1}.spm.tools.physio.model.retroicor.yes.order.c = 3;
matlabbatch{1}.spm.tools.physio.model.retroicor.yes.order.r = 4;
matlabbatch{1}.spm.tools.physio.model.retroicor.yes.order.cr = 1;
matlabbatch{1}.spm.tools.physio.model.rvt.no = struct([]);
matlabbatch{1}.spm.tools.physio.model.hrv.no = struct([]);
matlabbatch{1}.spm.tools.physio.model.noise_rois.no = struct([]);
matlabbatch{1}.spm.tools.physio.model.movement.yes.file_realignment_parameters = {''};
matlabbatch{1}.spm.tools.physio.model.movement.yes.order = 6;
matlabbatch{1}.spm.tools.physio.model.movement.yes.outlier_translation_mm = Inf;
matlabbatch{1}.spm.tools.physio.model.movement.yes.outlier_rotation_deg = Inf;
matlabbatch{1}.spm.tools.physio.model.other.yes.input_multiple_regressors = {'/Volumes/JW_min/JW/Ana_analyses/035/rp_a035run1_20150304_145309EPIfMRICyberballRound1s011a001.txt'};
matlabbatch{1}.spm.tools.physio.verbose.level = 2;
matlabbatch{1}.spm.tools.physio.verbose.fig_output_file = 'figures_035_R1';
matlabbatch{1}.spm.tools.physio.verbose.use_tabs = false;`
5. I should start updating the version I guess -> from tapas_physio_read_physlogfiles_siemens.m
 `Created: 2014-07-08
% Copyright (C) 2014 Institute for Biomedical Engineering, ETH/Uni Zurich.
%
% This file is part of the PhysIO toolbox, which is released under the terms of the GNU General Public
% Licence (GPL), version 3. You can redistribute it and/or modify it under the terms of the GPL
% (either version 3 or, at your option, any later version). For further details, see the file
% COPYING or <http://www.gnu.org/licenses/>.
%
% $Id: tapas_physio_read_physlogfiles_siemens.m 466 2014-04-27 13:10:48Z kasperla $
`

**Comment by mrikasper** [comment]
Dear @acmv1216,

Great, that helps a lot. Here are some observations:

1. I didn't see the information in the files you sent, maybe in the DICOM header of the image data you will find the Siemens software version, for our scanner, e.g., the following fields:
```
(0002,0013)	ImplementationVersionName	SYNGO_MR_XA30A
(0008,1090)	ManufacturerModelName	MAGNETOM Prisma
(0018,1020)	SoftwareVersions	syngo MR XA30
```
2. Yes, the parameters look normal, no multiband etc., but I am actually surprised that you get these file types then (rather than `.puls` or `.ext` files). Do you use the `ideaCmdTool` to start the physiological recordings?
3. I tried running your batch (after modifications, see (4)), and can reproduce your error. 
    - For me, it's related to having different time stamps in the `*AcquisitionInfo*.log` and `*PULS.log`. The logfiles are not matching (also not in their filename), and so the sampled time intervals do not match. Have a look at this plot:
![image](https://user-images.githubusercontent.com/13321311/154146179-63e5b7ba-5c45-4e93-a995-f73e6909b26b.png)
    - But this could be, because the two logs don't match, maybe you can attach `20150304_151945_PULS.log` and I can try again. 
    - Alternatively, you can use the attached version of `tapas_physio_create_scan_timing_from_tics_siemens.m` (you have to rename it and put it in the `code/sync` folder of PhysIO, and set `verbose.level = 3` to see the plot.
4. The batch:
   - The file you attached is not the one from the batch (`20150304_151945_PULS.log`)
   - NB: If you want to use motion models using the realignment parameter file (`rp_*.txt`), you have to add it as `physio.model.movement.yes.file_realignment_parameters ` rather than `physio.model.other.yes.input_multiple_regressors`. If the former is empty, but the motion model selected, it will probably give an error.
5. NB: The version in `tapas_physio_read_physlogfiles_siemens.m` is the last change of that file (which is up to date, I think), but some other files might have changed. Calling `tapas_physio_version` will give you the most precise version estimate.

[tapas_physio_create_scan_timing_from_tics_siemens.txt](https://github.com/translationalneuromodeling/tapas/files/8074534/tapas_physio_create_scan_timing_from_tics_siemens.txt)

I hope this helps!

All the best,
Lars

**Comment by acmv1216** [comment]
Dear Lars,

Many thanks for your help with this, it is greatly appreciated. Sorry about the mistakes, here goes the updated info. 

1. Software version is `SoftwareVersions: 'syngo MR D13D'`
2. Yes they have just confirmed they used that tool.
3. I have checked the *PULS.log files and to me, they looked way to similar in the 3 runs of the task. So I did look for a participant with clearly different *PULS.log files, and still it was the same error. Replacing the file you attached to calculate times from Siemens tics also did not work. So I do not know what to try next. I send you attached the *AcquisitionInfo.log and the *PULS.log for last participant and for the new one, together with the new batch for a different participant. 

```
Failed  'TAPAS PhysIO Toolbox'
Array indices must be positive integers or logical values.
In file "/Applications/tapas/PhysIO/code/tapas_physio_get_onsets_from_locs.m" (???), function "tapas_physio_get_onsets_from_locs" at line 105.
In file "/Applications/tapas/PhysIO/code/tapas_physio_create_scan_timing.m" (???), function "tapas_physio_create_scan_timing" at line 114.
In file "/Applications/tapas/PhysIO/code/tapas_physio_main_create_regressors.m" (???), function "tapas_physio_main_create_regressors" at line 138.
In file "/Applications/spm12/toolbox/PhysIO/tapas_physio_cfg_matlabbatch.m" (???), function "run_physio" at line 1463.
[042.zip](https://github.com/translationalneuromodeling/tapas/files/8079834/042.zip)

```
[035.zip](https://github.com/translationalneuromodeling/tapas/files/8079832/035.zip)
[042.zip](https://github.com/translationalneuromodeling/tapas/files/8079835/042.zip)
[PhysIO.zip](https://github.com/translationalneuromodeling/tapas/files/8079836/PhysIO.zip)

4. Thanks for the input, I changed it :) 

Any suggestion is more than welcome - I am not ready to give up just yet, as I know it will have a relevant impact on the analyses!

Thanks, 

A

**Comment by mrikasper** [comment]
Dear @acmv1216,

Great, thank you for the infos and the matching logfiles. I think I have found the issue:

- You set the number of dummy scans (`Ndummies`) to 3, but the acquisition log file does not contain these dummy scans, but just the 76 volumes (`Nscans`) that you need for your GLM. 
    - PhysIO's documentation is probably not super-clear here, but you have to just specify any dummies that produce actual imaging volumes in the run (and are actively discarded for the GLM analysis). Nowadays most scanners have the convenient option to run the dummy scans, but not saving them to file, so typically one has 0 dummies in the PhysIO sense.
    - I have updated `tapas_physio_get_onsets_from_locs` to give a less cryptic error message if the code fails because of that:
```
16-Feb-2022 23:32:26 - Failed  'TAPAS PhysIO Toolbox'
Error using tapas_physio_log (line 56)
Number of dummy slice event bundles does not match Ndummies. Check parameter sqpar.Ndummies or set to 0.
	 (Matlab error: Array indices must be positive integers or logical values.)
```
- If you instead set `sqpar.Ndummies` to 0, at least the first run of `035` runs through, the subject seems to have a regular, well identifiable heartbeat, please see the screenshots.
![image](https://user-images.githubusercontent.com/13321311/154406803-8cfcc44b-6b5a-497b-9aec-726cabfa0e1e.png)
![image](https://user-images.githubusercontent.com/13321311/154406867-8ed29e58-4725-4785-8b04-c2ad9e4f7e8e.png)
    - I have attached the code and batch I used, you will have to rename the files to `.m` and move them to `code/sync` again.
    - Please let me know whether this solves the issue also for the other runs. If so, I will update the code with these new error messages also for the next PhysIO release.

I hope that helps - thanks for not giving up just yet ;-)

All the best,
Lars
[physio_batch_LK.txt](https://github.com/translationalneuromodeling/tapas/files/8085598/physio_batch_LK.txt)
[tapas_physio_create_scan_timing_from_tics_siemens.txt](https://github.com/translationalneuromodeling/tapas/files/8085604/tapas_physio_create_scan_timing_from_tics_siemens.txt)
[tapas_physio_get_onsets_from_locs.txt](https://github.com/translationalneuromodeling/tapas/files/8085605/tapas_physio_get_onsets_from_locs.txt)

**Comment by acmv1216** [comment]
Dear Lars,

Really great all your help there, I think I am almost there. However, I think I would still need some help. When I get the new "tapas_physio_create_scan_timing_from_tics_siemens.m" function, I run into some issues. Some of them have to do with the expected input that does not match with that specified in line 97 of the script "tapas_physio_create_scan_timing.m" Input expected is tapas_physio_create_scan_timing_from_tics_siemens(ons_secs.t, log_files, verbose), but in the new function we have t (from ons_secs.t, **_t_start,_** log_files, verbose). I tried a workaround that issue (which does not mean I solved it) and then found next error `Undefined function 'tapas_physio_read_columnar_textfiles' for input arguments of type 'char'.` Which is at line 47 on our latest script to extract timing from siemens tics. So unfortunately there I have to stop, since I do not know how to fix it... 

Again, sorry to bother you so much with these questions and thanks a lot - at least I know it works, so I should be able to find the way to implement it. 

Thanks!

Best,

A

**Comment by mrikasper** [comment]
Dear @acmv1216,

It's great we are making progress. Here are my thoughts:

1. Is there any reason for you not to use the most recent version of PhysIO? I highly recommend the switch.
    - I just checked, and the introduction of the `t_start` parameter in the `tapas_physio_create_scan_timing_from_tics_siemens` happened in September 2017
    - Therefore, your version of the code doesn't enjoy all of the bugfixes (a lot of them related to SIEMENS logfile timing, though mostly for VB, but also a major timing issue related to how we compute the convolution in the respiratory and cardiac response model) and preprocessing improvements (mostly for respiratory data, see [Sam Harrison's paper](https://doi.org/10.1016/j.neuroimage.2021.117787), but also some related to PPU filtering)
    - A list of all changes since then can be found in the [CHANGELOG](https://github.com/translationalneuromodeling/tapas/blob/master/PhysIO/CHANGELOG.md)
    - To reassure you, we run unit and integration tests for all example logfiles with every new release, so there should be backwards compatibility for the data you have processed before. The old batch files might give some warnings about new fields when you load them, but the existing parameters should still be set properly
 2. If you want to keep using the old version, all of the changes I made to the functions were in relation to debugging plots and clearer error messages. I think your original code might also run just fine if you set `sqpar.Ndummies = 0` in the batch.

Let me know how it goes and

All the best,
Lars

**Comment by acmv1216** [comment]
Dear Lars, 

It now all works nicely!! thanks a lot! We will implement this in our participants and will get back to you if I happen to have any issues. Thanks again!

Best,

A
