### ISSUE TITLE
PhysIO error

### ISSUE THREAD

**Issue by alireza-kr** [translationalneuromodeling/tapas#187]
I am trying to denoise preprocessed fMRI data using TAPAS PhysIO Toolbox. The data has been preprocessed with SPM. I used the batch files here (https://www.nitrc.org/forum/message.php?msg_id=26272) for denoising; however, I got the following error:

> Failed  'TAPAS PhysIO Toolbox'
> Reference to non-existent field 'cm'.
> In file "D:\Software\MATLAB Toolbox\spm12\toolbox\PhysIO\model\tapas_physio_create_noise_rois_regressors.m" (???), function "tapas_physio_create_noise_rois_regressors" at line 186.
> In file "D:\Software\MATLAB Toolbox\spm12\toolbox\PhysIO\tapas_physio_main_create_regressors.m" (???), function "tapas_physio_main_create_regressors" at line 360.
> In file "D:\Software\MATLAB Toolbox\spm12\toolbox\PhysIO\tapas_physio_cfg_matlabbatch.m" (???), function "run_physio" at line 1661.

I commented the following lines in 'tapas_physio_create_noise_rois_regressors.m' and the problem solved:
```
% Overlay the final noise ROI (code from spm_orthviews:add_c_image)
    if verbose.level >= 2
        spm_orthviews('addcolouredimage',r,Vroi.fname ,[1 0 0]);
        hlabel = sprintf('%s (%s)',Vroi.fname ,'Red');
        c_handle    = findobj(findobj(st.vols{r}.ax{1}.cm,'label','Overlay'),'Label','Remove coloured blobs');
        ch_c_handle = get(c_handle,'Children');
        set(c_handle,'Visible','on');
        uimenu(ch_c_handle(2),'Label',hlabel,'ForegroundColor',[1 0 0],...
            'Callback','c = get(gcbo,''UserData'');spm_orthviews(''context_menu'',''remove_c_blobs'',2,c);');
        spm_orthviews('redraw')
    end
```

Is it ok to do so because I have no idea why I got the error?

**Comment by mrikasper** [comment]
Dear Alireza,

This is an error related to visualization if the images have different resolutions are are resliced during noise ROIs extraction. I have attached a bugfix and more detailed explanation in [this thread](https://github.com/translationalneuromodeling/tapas/issues/162#issuecomment-1095270736).

My apologies for the inconvenience, we will include the bugfix in the next release.

If you set `verbose.level = 1`, it should also not occur. Commenting it out like you did is also OK and only affects visualization of the ROIs used for noise extraction.

All the best,
Lars

**Comment by alireza-kr** [comment]
Thank you!
