### ISSUE TITLE
tapas_simModel in HGF 6.0 not compatible with tapas_rw_binary

### ISSUE THREAD

**Issue by dsstolz** [translationalneuromodeling/tapas#188]
I have noticed that new lines have been inserted (166-176) in tapas_simModel, serving to:
% Check inferred states for NaN values (due to numerical problems when taking log)

This code requires the existence of r.traj to contain muhat and sahat, which is not the case for, e.g., tapas_rw_binary, which produces v instead of muhat. Therefore, using tapas_simModel from version 6.0 is incompatible with rw models (and possibly others that to not produce muhat and sahat).

**Comment by alexjhess** [comment]
Dear @dsstolz,

Thank you for pointing this out! We are working on a solution and will notify you once we have fixed it.

Best wishes,
Alex

**Comment by chmathys** [comment]
A bugfix release will happen in the coming days

**Comment by chmathys** [comment]
[Bugfix release](https://github.com/translationalneuromodeling/tapas/releases/tag/v6.0.1)
