### ISSUE TITLE
Problem with post-hoc manual peak selection

### ISSUE THREAD

**Issue by MichaKeller** [translationalneuromodeling/tapas#19]
Hello,

we are using the Biopac system to record PPG and respiration. 

First of all, I would like to refer to another post by DanielHoffmann. They also used biopac and we experienced similar difficulties in terms of peak detection of the PPG data. To get rid of the strong baseline fluctuations we also decided to implement a filter which resolved the problem for most of our data. 

However, it did not completely resolve the problem as we still have peaks which have not been correctly identified. That's why we would like to use the manual peak selection which unfortunately does not work. 

> Running 'TAPAS PhysIO Toolbox'
> No cardiac R-peak (heartbeat) events provided
> Failed  'TAPAS PhysIO Toolbox'
> Error using close
> Invalid figure handle.
> In file "C:\Program Files\MATLAB\R2015b\toolbox\matlab\graphics\close.p" (???), function "close" at line 0.
> In file "D:\Datensicherung\BPS Projekt_18.1.2018\PhysIO\tapas_physio_correct_cardiac_pulses_manually.m" (???), function "tapas_physio_correct_cardiac_pulses_manually" at line 106.
> In file "D:\Datensicherung\BPS Projekt_18.1.2018\PhysIO\tapas_physio_main_create_regressors.m" (???), function "tapas_physio_main_create_regressors" at line 169.
> In file "D:\spm12\toolbox\PhysIO\tapas_physio_cfg_matlabbatch.m" (???), function "run_physio" at line 1467.
> 
> The following modules did not run:
> Failed: TAPAS PhysIO Toolbox
> 
> Error using MATLABbatch system
> Job execution failed. The full log of this run can be found in MATLAB command window, starting with the lines (look for the line showing the exact #job as
> displayed in this error message)

Do you have any idea why this error occurs? Do you need more information? 

I'm looking forward to your reply. Thank you very much in advance!

Best,
Micha

**Comment by mrikasper** [comment]
Dear Micha,

thank you for using the toolbox. For manual peak selection, PhysIO has to actually determine that there are outliers in your heart-beat detection. It does that by comparing a representative percentile of the beat-to-beat duration (default: 80) to the beat-to-beat durations. You can then specify a lower and upper threshold (in percent, default: 60%/60%), outside which the interval will be flagged as an outlier (additional/missing heart beats).

Here are the lines and explanations in `tapas_physio_new`, but you can also find them in the Batch Editor GUI:

```
   % Suspicious positions of missing or too many cardiac pulses are
    % pre-selected by detecting outliers in histogram of
    % heart-beat-2-beat-intervals
    preproc.cardiac.posthoc_cpulse_select.percentile = 80; % percentile of beat-2-beat interval histogram that constitutes the "average heart beat duration" in the session
    preproc.cardiac.posthoc_cpulse_select.upper_thresh = 60; % minimum exceedance (in %) from average heartbeat duration to be classified as missing heartbeat
    preproc.cardiac.posthoc_cpulse_select.lower_thresh = 60; % minimum reduction (in %) from average heartbeat duration to be classified an abundant heartbeat
```

If there are no outliers detected (see diagnostics figure below), the outlier detection would be skipped. 

![nomissingheartbeats](https://user-images.githubusercontent.com/13321311/41098847-079a4904-6a5d-11e8-9d77-cba15746168c.PNG)

However, there was actually a bug (which you ran into), if there are no outliers found, to close a non-existing figure. I will fix this in the next release, or you can also just comment line 63 of `tapas_physio_correct_cardiac_pulses_manually`

```
close(verbose.fig_handles(end));
```

If you choose the thresholds differently (more conservative, e.g, 20 or 40 %), you should be able to manually correct these heartbeats. Check that your diagnostics figure (usually Figure 5) looks like that, flagging the suspicious heart beats:

![missingheartbeats](https://user-images.githubusercontent.com/13321311/41098385-793c33ee-6a5b-11e8-9c4a-7eddc64c717b.PNG)


Of course, the more principled solution is to find the appropriate filters for your drift phenomenon on the data before the detection.

All the best,
Lars
