### ISSUE TITLE
Question about concatenated data

### ISSUE THREAD

**Issue by Domi0222** [translationalneuromodeling/tapas#199]
Hi everyone!

Thanks for the great work.
Currently, I’m trying to implement HGF models in my experiment. 

We conducted a beads task consisting of 10-beads × 4 sequences (the same condition as Adams et al., 2018 The journal of neuroscience https://www.jneurosci.org/content/38/44/9471).

Like Adams et al., we concatenated all sequences for each subject to estimate the model parameters as accurately as possible (resetting the beliefs about the jars at the start of each sequence).

Due to adding the beliefs for reset, we have response sequences 43 trials(10-beads × 4 sequences + 3 beliefs for reset),　while input (u) has only 40 trials(10-beads × 4 sequences).

How can I resolve this gap between the number of trials in input and responses?

**Comment by chmathys** [comment]
Hi Domi - I see that this question is still open. In the study you mention, we reset the beliefs about the jars at the start of each sequence (without creating an extra input to do that, afaik). If you're interested in the exact code used, please contact the first author.
