### ISSUE TITLE
tapas_download_example_data

### ISSUE THREAD

**Issue by Ruwanmri** [translationalneuromodeling/tapas#214]
Hi,

I get the following error when trying to download example data. Could you please let me know how to fix this issue?

Error: File: tapas_download_example_data.m Line: 23 Column: 8
Unable to find or import 'JavaMD5.JavaMD5'. Imported names must end with '.*' or be fully qualified.

I am a new TAPAS PhysIO toolbox user. PhysIO Installation seems okay.

Thank you.

Ruwan

**Comment by mrikasper** [comment]
Dear Ruwan,

Thank you for trying out PhysIO. Did you run `tapas_init` (*note*: not the same as `tapas_physio_init`!) before calling `tapas_download_example_data`?

All the best,
Lars
