### ISSUE TITLE
Power analysis for HGF

### ISSUE THREAD

**Issue by Yintje** [translationalneuromodeling/tapas#219]
Hi all,

I'm trying to design an experiment with HGF as the statistical analysis. I was wondering how you can decide how many trials are needed and how many participants are needed for this model? Anyone has experience in this?

**Comment by BPaton** [comment]
Hi Yintje,

It depends quite a bit on what your research question is. Are you
interested in differences amongst people for one or more tasks in terms of
a particular model parameter? Are you instead interested in what model(s)
best fit an individual's responses and how might these best fitting models
differ across people or tasks e.g. half the sample the RW fits best but the
other half the 3 level binary eHGF does?

You could think of it slightly the other way, use the HGF simulation tools
to generate data responses and Bayes optimal observer fits to the models
you are interested in comparing, simulate a reasonable number of
"participants/subjects" and run the model comparison. Repeat and adjust the
parameters until you get a clear separation in models. I recently ran an
experiment and tuned a set of parameters for the experiment, specifically
how the stimuli moved, using the HGF by setting the parameters in question
based on how much the highest level volatility responded to an optimal
observer trying to follow the stimuli (with a mouse). In other words this
choice of parameters evokes a specific highest level volatility response.

Thanks.

Bryan.
