### ISSUE TITLE
PhysIO: Channels are not parsed for logfile version 3 from Vida scanner

### ISSUE THREAD

**Issue by SaskiaBollmann** [translationalneuromodeling/tapas#220]
Hi,

I have logfiles from a Siemens Vida scanner with logversion 3, and although the physio wiki says this data should be read-in, the channels are not parsed correctly. Is there a special setting that's necessary to enable this? 

![image](https://user-images.githubusercontent.com/25474977/207472914-364bf26a-236f-48bb-8d7b-ed3961e95f1a.png)

Thanks,
Saskia

**Comment by mrikasper** [comment]
Dear Saskia,

Thank you for trying PhysIO. This should be supported with the upcoming TAPAS Release that includes PhysIO R2022b-v8.2.

The release should happen in the next few days. Meanwhile, you can download PhysIO v8.2 already from the [physio-branch](https://github.com/translationalneuromodeling/tapas/tree/physio) of TAPAS.

All the best,
Lars
