### ISSUE TITLE
PhysioIO: Errors while running example during installation

### ISSUE THREAD

**Issue by sarahbakirci** [translationalneuromodeling/tapas#224]
Dear TAPAS Team,

I hope all is well. I am a PhD student  interested in using your tool to extract heart data data from Philips and GE machines in order to assess heart rate variability during task. I have installed TAPAS and its dependencies as outlined here:
https://github.com/translationalneuromodeling/tapas/blob/master/PhysIO/README.md

However, when running the example outlined, I do obtain a figure but I also run into the below errors.:
philips_ecg3t_matlab_script
Error using tapas_physio_log
tapas_physio_findpeaks_compatible is no longer
distributed with this toolbox. Instead, we rely on the "findpeaks"
function included in Matlab's Signal Processing Toolbox.

Error in tapas_physio_findpeaks (line 43)
    tapas_physio_log(sprintf(...

Error in tapas_physio_rescale_gradient_gain_fluctuations (line 64)
[~, idxGainPlus] = tapas_physio_findpeaks((dmG), 'minpeakDistance', n, ...

Error in tapas_physio_create_scan_timing_from_gradients_philips (line 175)
    tapas_physio_rescale_gradient_gain_fluctuations(...

Error in tapas_physio_create_scan_timing (line 83)
            tapas_physio_create_scan_timing_from_gradients_philips( ...

Error in tapas_physio_main_create_regressors (line 165)
            [ons_secs, VOLLOCS, LOCS, verbose] = tapas_physio_create_scan_timing(...

Error in philips_ecg3t_matlab_script (line 75)
physio = tapas_physio_main_create_regressors(physio);

Could you kindly provide assistance? I use a Mac. 

Many thanks!
Sarah

**Comment by mrikasper** [comment]
Dear Sarah,

Thank you for trying out PhysIO. You will have to install the signal processing and the statistics toolbox of Matlab in order to use PhysIO’s full functionality. Have a look at the [Requirements](https://github.com/translationalneuromodeling/tapas/blob/master/PhysIO/requirements.txt) file mentioned in the README.

Your error message already gives you some indication about that:

> Error using tapas_physio_log
> tapas_physio_findpeaks_compatible is no longer
> distributed with this toolbox. Instead, we rely on the "findpeaks"
> function included in Matlab's Signal Processing Toolbox.

I hope that helps!

All the best,
Lars
