### ISSUE TITLE
Using raw physio data without DICOM files

### ISSUE THREAD

**Issue by dorottyalantos** [translationalneuromodeling/tapas#44]
Hi, 
I recently conducted an fMRI study on a Siemens Prisma scanner while measuring respiration and pulse. I have some hypotheses that correspond only to my respiration and pulse measurements. I ran the Tapas script (including the DICOM, PPU, and Resp files) to preprocess the data. I am wondering where in the final .mat outputs can I find the transformed raw data corresponding to the PPU and resp files, and the pre-processed data corresponding to these measures. I believe that I should find some output here that I can use on its own (without the brain scans) for the purpose of testing my hypotheses relating to only these files, but I am not sure where I can find them. Ideally I am looking for output that I can import into programs used to analyse heart-rate related data (e.g., Kubios or labchart).
Thank you for your comments!
Dorottya

**Comment by mrikasper** [comment]
Dear Dorottya,

thank you for using PhysIO. Have a look at [question 9 of the FAQ](https://gitlab.ethz.ch/physio/physio-doc/wikis/FAQ#9-i-want-to-access-subjects-physiological-measures-eg-heart-rate-or-respiratory-volume-per-time-before-they-enter-the-regressors-where-can-i-do-that), this might already answer your question.

Let me know if anything remains unclear. I am not familiar with Kubios or labchart, but if they accept plain text files you can certainly export physio-variables via matlab, for example for the heart rate:

```
heartRate = physio.ons_secs.hr;
save('heartRate.txt', 'heartRate', , '-ascii');
```

All the best,
Lars
