### ISSUE TITLE
Fitting multi-session learning data with HGF

### ISSUE THREAD

**Issue by akshaynair1** [translationalneuromodeling/tapas#7]
Hi Chris,
 
We met at the SPM course last year in your fMRI workshop. I hope you don’t mind me asking a quick follow-up question re: the hgf toolbox.
 
If you have learning data from two fmri sessions how do you fit multi-session data using HGF? Can you specify data from two sessions but one subject?
 
Thanks,
 
Akshay

**Comment by chmathys** [comment]
Hi Akshay,

There are many ways to deal with this, and which you choose depends on the details of your experiment. Some possibilities are:

- You could analyze the sessions separately, treating the estimated parameters as two observations at the subject-level in a multilevel model

- You could concatenate your data to give you one virtual session *if* you can argue that subjects were likely to pick up exactly where they left off

- You could use the end state of the belief trajectories after the first session as the initial values in the second session while estimating the parameters separately for the two sessions

- Future versions of the toolbox will be able to estimate parameters hierarchically, but it will still be a while before we can do hierarchies with both a between and within-subject level.

You may have additional ideas about what to do. The message here is that whatever you do, you will have to justify it in terms of the *specific experiment* you did.

Best wishes,
Chris
