### ISSUE TITLE
Error using taps_Cov2Corr

### ISSUE THREAD

**Issue by cmill22** [translationalneuromodeling/tapas#93]
Dear Dr Mathys,

I'm a beginner with computational modelling and the HGF and am currently trying to estimate subject-specific Bayes Optimal parameters to use as priors (as subjects each see a unique order of binary inputs) with the following code:

BayesOpt_params = tapas_fitModel([],...                             
                      u,...                                            
                      'tapas_hgf_binary_config_BayesOptModel1',...      
                      'tapas_bayes_optimal_binary_config',...           
                      'tapas_quasinewton_optim_config');        

1. During this procedure I keep encountering the error 'Error using tapas_Cov2Corr (line 14)
Input matrix is not symmetric.' for all or at least some subjects. Would you be able to advise me on how to counteract this error? 

2. I am confused why om values must be negative- I understood this parameter to represent tonic volatility at each level (so therefore should be positive?)

My tapas_hgf_binary_config is:

c.mu_0mu = [NaN, 1, 0]; 
c.mu_0sa = [NaN, 0.5, 1];

c.logsa_0mu = [NaN,   log(10), log(10)];
c.logsa_0sa = [NaN,          10,      10];

c.rhomu = [NaN, 0, 0];
c.rhosa = [NaN, 0, 0];

c.logkamu = [NaN, log(1)];
c.logkasa = [NaN,      5];

c.ommu = [NaN,  -10,  -10];
c.omsa = [NaN, 4^2, 4^2];

Thank you so much for your kind help and very best wishes,
Chantal

**Comment by chmathys** [comment]
Dear Chantal,

1. The error you keep encountering is the result of some internal changes in Matlab. We’re aware of this and are working to fix it. If you have access to an older version of Matlab, that might help in the meantime.

2. The omegas are tonic *log*-volatilities, that’s why they can and often do take negative values. They can also be positive, though.

Best wishes,
Christoph
