### ISSUE TITLE
PhysIO: Failed to generate F-Contrast and postscript file

### ISSUE THREAD

**Issue by AM742** [translationalneuromodeling/tapas#95]
Hi,
I’m currently trying to assess the quality of noise correction with an F-Contrast over all physiological nuisance regressors (9 respiratory regressors and 6 movement regressors) using the function  “tapas_physio_report_contrasts” via the PhysIO toolbox. However, calling the function from the command line does not generate an F-Contrast or a postscript file in the single subject analysis folder. Moreover, MATLAB does not produce an error message. Both the SPM.mat file and the physio.mat files of each subject are in the respective single subject analysis folders. I’ve already checked and the input seems ok. The SPM.mat file analysis folder holds all the regressors of interest and nuisance regressors of both experimental sessions and the two physio.mat files hold the PhysIO-object of each session, respectively. Do you have any advice what to look for in order to generate the F-Contrast and postscript file? 

Thank you very much in advance.
AM

**Comment by mrikasper** [comment]
Dear AM,

my apologies for the late reply. This is indeed very surprising behavior - I would have at least expected some kind of error message. Could you specify the exact command you ran in the command window?

If you are familiar with the Matlab debugger, maybe you can set a breakpoint at the start of `tapas_physio_report_contrasts` step through the function to see whether it does anything at all. I'm also curious if it creates new contrasts in the `SPM.mat`. You could check this in the SPM GUI by clicking on the Results button, selecting the same `SPM.mat` as for `tapas_physio_report_contrasts` and see whether new contrasts were created that relate to the physiological inputs.

As an aside: How do you end up with exactly 9 respiratory regressors? 4th order RETROICOR and RVT?

All the best,
Lars
