### ISSUE TITLE
including realignment parameters/additional regressors when time window of recording is different to physio recordings

### ISSUE THREAD

**Issue by gjoue** [translationalneuromodeling/tapas#99]
Hi Lars,

I see that PhysIO simulates data which it prepends to the cardiac and respiratory signal when the physiological recordings were started after MRI scanning, but it doesn't handle the mismatch between physiological files and the length of additional regressor files (like realignment parameters or other regressors)? 

Sorry, I didn't really look too deeply in the code -- just saw that prepending simulated data happens when the physiological files are loaded, and although additional regressors are concatenated together afterwards (l.367 in `tapas_physio_main_create_regressors()`), an error is thrown when these additional regressors are concatenated with the physio data in the call to `tapas_physio_orthogonalise_physiological_regressors()` in the line directly after that in trying to concatenate vectors of different dimensions.

I have uploaded an example problematic set of additional regressor files (realignment parameters, spikes) and physio logs in BIDS format here in case:
https://gigamove.rz.rwth-aachen.de/d/id/8BVM7vHSqAUULX

Thanks!
Gina

**Comment by mrikasper** [comment]
Dear Gina,

my sincere apologies for overlooking this issue, the Corona summer season has left quite a backlog on my todo-lists, as for everyone, I assume. The link you provided is no longer valid, I'm afraid, could you send it again, please?

The simulation of cardiac/respiratory signal is an experimental feature I haven't fully tested yet. So no guarantees that it works. But I can have a look whether there is an easy solution to your question of matching additional regressors of different length, if I see the example data.

All the best,
Lars
